<?php

namespace ContainerHl38cOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EeEAcwIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eeEAcwI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eeEAcwI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.NxZ6k06', 'get_ServiceLocator_NxZ6k06Service', true],
            'App\\Controller\\MessageController::store' => ['privates', '.service_locator.2hevt6o', 'get_ServiceLocator_2hevt6oService', true],
            'App\\Controller\\MessageController::update' => ['privates', '.service_locator.H42bztt', 'get_ServiceLocator_H42bzttService', true],
            'App\\Controller\\TicketController::store' => ['privates', '.service_locator.MIGI5yh', 'get_ServiceLocator_MIGI5yhService', true],
            'App\\Controller\\TicketController::update' => ['privates', '.service_locator.4xy6poZ', 'get_ServiceLocator_4xy6poZService', true],
            'App\\Controller\\TicketStatusController::update' => ['privates', '.service_locator.UrgZlSf', 'get_ServiceLocator_UrgZlSfService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.NxZ6k06', 'get_ServiceLocator_NxZ6k06Service', true],
            'App\\Controller\\MessageController:store' => ['privates', '.service_locator.2hevt6o', 'get_ServiceLocator_2hevt6oService', true],
            'App\\Controller\\MessageController:update' => ['privates', '.service_locator.H42bztt', 'get_ServiceLocator_H42bzttService', true],
            'App\\Controller\\TicketController:store' => ['privates', '.service_locator.MIGI5yh', 'get_ServiceLocator_MIGI5yhService', true],
            'App\\Controller\\TicketController:update' => ['privates', '.service_locator.4xy6poZ', 'get_ServiceLocator_4xy6poZService', true],
            'App\\Controller\\TicketStatusController:update' => ['privates', '.service_locator.UrgZlSf', 'get_ServiceLocator_UrgZlSfService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\MessageController::store' => '?',
            'App\\Controller\\MessageController::update' => '?',
            'App\\Controller\\TicketController::store' => '?',
            'App\\Controller\\TicketController::update' => '?',
            'App\\Controller\\TicketStatusController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\MessageController:store' => '?',
            'App\\Controller\\MessageController:update' => '?',
            'App\\Controller\\TicketController:store' => '?',
            'App\\Controller\\TicketController:update' => '?',
            'App\\Controller\\TicketStatusController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
