<?php

namespace ContainerHl38cOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2hevt6oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2hevt6o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2hevt6o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', 'App\\Requests\\StoreTicketMessageRequest', 'getStoreTicketMessageRequestService', true],
        ], [
            'request' => 'App\\Requests\\StoreTicketMessageRequest',
        ]);
    }
}
