<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQz18ScZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQz18ScZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQz18ScZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQz18ScZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQz18ScZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qz18ScZ',
    'container.build_id' => '498cd67c',
    'container.build_time' => 1653650863,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQz18ScZ');
