<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeDMn6m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeDMn6m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUeDMn6m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUeDMn6m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUeDMn6m\App_KernelDevDebugContainer([
    'container.build_hash' => 'UeDMn6m',
    'container.build_id' => '1a9739a5',
    'container.build_time' => 1653312168,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeDMn6m');
