<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJq1IAzs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJq1IAzs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJq1IAzs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJq1IAzs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJq1IAzs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jq1IAzs',
    'container.build_id' => '970d3117',
    'container.build_time' => 1653566140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJq1IAzs');
