<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'tickets-get' => [[], ['_controller' => 'App\\Controller\\TicketController::index'], [], [['text', '/api/tickets']], [], [], []],
    'tickets-post' => [[], ['_controller' => 'App\\Controller\\TicketController::store'], [], [['text', '/api/tickets']], [], [], []],
    'ticket-get' => [['ticketId'], ['_controller' => 'App\\Controller\\TicketController::show'], [], [['variable', '/', '[^/]++', 'ticketId', true], ['text', '/api/tickets']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
