version: '3.7'
services:

    #PHP Service
    supservice-core:
        build:
            context: .
            dockerfile: Dockerfile
        image: supservice-core
        container_name: supservice-core
        command: bash -c "php bin/console cache:clear && php bin/console doctrine:schema:update --force && php-fpm"
        restart: unless-stopped
        tty: true
        env_file:
            - .env
        environment:
            SERVICE_NAME: supservice-core
            SERVICE_TAGS: dev
            DB_HOST: mysql
        working_dir: /var/www/html
        volumes:
            - ./docker-configs/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - mysql
        networks:
            - supservice-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8081:80"
            - "444:443"
        volumes:
            - ./:/var/www/html
            - ./docker-configs/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - supservice-core
        networks:
            - supservice-network

    #MySQL Service
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        command: mysqld --init-file="/etc/mysql/init/init.sql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - mysql:/var/lib/mysql
            - ./docker-configs/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker-configs/mysql/init.sql:/etc/mysql/init/init.sql
        networks:
            - supservice-network

#Docker Networks
networks:
    supservice-network:
        name: supservice-network
        driver: bridge

#Volumes
volumes:
    mysql:
        driver: local
