<?php

namespace ContainerUeDMn6m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H42bzttService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H42bztt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H42bztt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', 'App\\Requests\\UpdateTicketMessageRequest', 'getUpdateTicketMessageRequestService', true],
        ], [
            'request' => 'App\\Requests\\UpdateTicketMessageRequest',
        ]);
    }
}
